[lightning]
# Logging
file = "/home/tidb-lightning.log"
level = "debug"

[tikv-importer]
# Uses the Local-backend
backend = "local"
# Sets the directory for temporarily storing the sorted key-value pairs.
# The target directory must be empty.
disk-quota = "500MB"
sorted-kv-dir = "/tmp/sst"

[checkpoint]
enable = false

[mydumper]
# Local source data directory
data-source-dir = "/home/temp"

# Configures the wildcard rule. By default, all tables in the mysql, sys, INFORMATION_SCHEMA, PERFORMANCE_SCHEMA, METRICS_SCHEMA, and INSPECTION_SCHEMA system databases are filtered.
# If this item is not configured, the "cannot find schema" error occurs when system tables are imported.
filter = ['*.*', '!mysql.*', '!sys.*', '!INFORMATION_SCHEMA.*', '!PERFORMANCE_SCHEMA.*', '!METRICS_SCHEMA.*', '!INSPECTION_SCHEMA.*']
[tidb]
# Information of the target cluster
host = "127.0.0.1"
port = 4000
user = "root"
# Table schema information is fetched from TiDB via this status-port.
status-port = 10080
# The PD address of the cluster
pd-addr = "127.0.0.1:2379"

[cron]
check-disk-quota = "5s"
